[package]
name = "clipboard-script"
version = "0.1.0"
authors = ["Douman <douman@gmx.se>"]
edition = "2018"

[[bin]]
name = "furi_clean"
path = "src/furi_clean.rs"

[dependencies]
clipboard-master = "3"
clipboard-win = "4"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
